### ISSUE TITLE
Source Command Not Respecting JSON Flag

### ISSUE THREAD

**Issue by ssmiller25** [BlueMedoraPublic/bpcli#30]
On latest version of bpcli, the `--json` flag does not appear to work with sources.  Example:
```
[smiller@smiller-mbp:bindplane-infra/jenkins]% bpcli version
Bindplane CLI version: 1.2.0
[smiller@smiller-mbp:bindplane-infra/jenkins]% bpcli source list --json
id: 81be3392-cd06-48c2-b849-0f73988e4947 source_type: postgresql status: Active
id: 6b6d7905-a120-41de-a3a6-077b7033cd15 source_type: postgresql status: Active
id: 601d1d9a-e6f1-4d3a-bd4e-c07c5bc4f495 source_type: postgresql status: Active
id: 1e26cb18-0cbd-4fc1-95b0-062cac382c4c source_type: postgresql status: Active
.....
```
(Note: UUIDs are from test system, so left in as not considered sensitive)

**Comment by jsirianni** [comment]
`--json` is a global flag, so it show sup with `bpcli source help`, however, it is ignored on purpose for `bpcli source list`. 

With that said, adding it should be fine, and it will not break backwards compatibility.
